name: CI with latest GRASS GIS

on:
  push:
  pull_request:
  schedule:
  # 01:00 Pacific Time (in UTC), every day (morning)
  - cron:  '0 8 * * *'

jobs:
  test-with-compiled:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    
    - name: Get dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget git gawk findutils
        xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
            sudo apt-get install -y --no-install-recommends --no-install-suggests
    - name: Create installation directory
      run: |
        mkdir $HOME/install
    - name: Set number of cores for compilation
      run: |
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
    - name: Set LD_LIBRARY_PATH for GRASS GIS compilation
      run: |
        echo "LD_LIBRARY_PATH=$HOME/install/lib" >> $GITHUB_ENV
    - name: Get and build GRASS GIS
      run: .github/workflows/build.sh $HOME/install
    - name: Add the bin directory to PATH
      run: |
        echo "$HOME/install/bin" >> $GITHUB_PATH
    - name: Make simple grass command available
      run: |
        ln -s $HOME/install/bin/grass* $HOME/install/bin/grass
    - name: Install the module
      run: |
        grass --tmp-location XY --exec g.extension extension=r.futures url=./r.futures/ --verbose
    - name: Cache data for testing
      id: cache-nc_spm_08_grass7
      uses: actions/cache@v1
      with:
        path: nc_spm_08_grass7
        key: ${{ runner.os }}-nc_spm_08_grass7
    - name: Get sample data for testing (NC SPM sample location)
      if: steps.cache-nc_spm_08_grass7.outputs.cache-hit != 'true'
      run: |
        grass --tmp-location XY --exec g.extension g.download.location --verbose
        grass --tmp-location XY --exec g.extension r.object.geometry --verbose
        grass --tmp-location XY --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz dbase=~ --verbose
    - name: Run test (manually specified files)
      run: |
        cd ./r.futures/r.futures.pga/testsuite
        grass -c ~/nc_spm_08_grass7/test --exec ./test_r_futures_pga.py
        cd ../../r.futures.devpressure/testsuite
        grass ~/nc_spm_08_grass7/test --exec ./test_r_futures_devpressure.py
        cd ../../r.futures.parallelpga/testsuite
        grass ~/nc_spm_08_grass7/test --exec ./test_r_futures_parallelpga.py
        cd ../../r.futures.calib/testsuite
        grass ~/nc_spm_08_grass7/test --exec ./test_r_futures_calib.py
        cd ../../r.futures.potsurface/testsuite
        grass ~/nc_spm_08_grass7/test --exec ./test_r_futures_potsurface.py
        cd ../../r.futures.demand/testsuite
        grass ~/nc_spm_08_grass7/test --exec ./test_r_futures_demand.py
        rm -rf ~/nc_spm_08_grass7/test
